apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgBAkyEqPaVt+aUglCveNrJLahygyafZVpK1mh3jLF/hNYKfLSPjo+7+awFcpLB3VREpDZXt8Ff2aVij0YXPM1/RPEFv7PJzeftCSXJQheezTGHk19SnJg9u2mGFx+aPrKb3kYnLZ/32tGNGALuOaCInOyTINbvXSr13L1KO8Zw9kkDXxUWlXGYTF9FUmTJpiCaNktmmfpoEjdxhIEctXy7/fYPOv7xPxIOYpQlNXnB5tiP6gN21WvRqMb1+TideuOeRbrBxTGum6Z9bYQyrMWrIomtIF9lCGB6oUrhkmpFd/2BFbsdlKrbUT1Qacd0B9DjvUxPle+TgpHgKCrzV7XincY53YqYFe4fhJnL969JaSCD3jEBfAuCnGPnUTasb9fZgFlGv77bRPP3JkDEuyEXNMO5xZ4357VOmWZazvoMFo7b57Ru7LN5h/7eeqA5b4UXbPAucsw+GLJNxL3xvF32zncqU/3Sp6S4op0/l9tqYUwk8USPCL/nzDhzyKqg5hHg8iw/7pX5PjOoM2281JeXg0/ZaNRdKNG2w6f6rlqgAOxkcCn6g53vI0THDF1a6RzP+/EUM3tvA6JLrF+2hebovAEZVfkn0Wo9IWLXInhcqXIqe0gnGPCS4ieOTYtk5QCW1uFUpYCtLRcRRX689cGpyTpihKsWFLL6SbaXiXYpxFdnCqMEFgm8yeuBHRVQtO1v7hIYFsMmojFk4tjRkFVX4YIjNz9N91yZJIK4EipsIeMnhmPycegof
    username: AgCBTSA3Synr7askha10pq//ohsvb3nrVu5uR2mQj+GSBYy4go4wDeLMW+E1lnqqvrIbg56oTYBJw0OyYYOPKubbmPrZbkipg+EubD9/GxR/J9JWHys0+gSPAyV2yq/nj/I842+GlM56iaLwfCPkVwH7R25b+I5RUUkOa/S4++HNTy5tpYWeyrcvODCpTyVI2QsvU4CO4dSPlHxYmwrlBunBbfvWnCFosL7RdWxVAIcYAgEEsapQKTE5PUDaA/vSJS1Sdae7dIU2EJvo6a5pDxhtH4FLiBKmWoy1Xsgi1tpgowkOjKsM+of1pV4644oY3tvt6mZ4cAo66D2WtA2SmTFxjmjEhLjJOCSDYr6rHQzM+OyfCF6lCtQHlGD3OlMpYZIRRey57QhTDyCk1IBjGXlQ9trMCoYWfroFQ8geKCVMhxF+6ZXrlQKuUYsmAdEUNrJjesEaauWaAwUtGJRhpwissMLrdI2Lkc30QQU26MAakk5by4a8edfVCwXRd0iq2ausTY/eLCiIe25GeJx2IG4W3bBCl+cmWP7akGif4uj9rdcnsMUba37ldjGEEdeYmPYy47BmsIqpU/YhFRIOmlef8pQLQQ/iLRLPJKBar3a7YUGaNfOno2sTo02Z38h8GYCkhWEx2ALJrPyKYHvYWxJ8X82Lwd7CJgjZDswzPhM9DQWBVXvNL7ttilihX4f4PeuvlCnBl/QPynROI2s=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

